"""Audio analysis and the output measurements, against synthesised fixtures.

These are the checks the system uses to decide whether a render is any good, so
they need ground truth rather than a comparison against last time. Every fixture
is generated by ffmpeg: a 120 BPM click train really is 120 BPM, a black frame
really is black, and a video that flashes at 1s and 5s flashes only there.
"""

from __future__ import annotations

import numpy as np
import pytest

from lyricfield import analysis as A
from lyricfield import render as R

pytestmark = pytest.mark.ffmpeg


# ------------------------------------------------------------------- decode

def test_decode_gives_the_expected_length(sine_wav):
    x = A.decode_mono(sine_wav)
    assert len(x) == pytest.approx(2 * A.SR, rel=0.02)


def test_decode_is_mono_regardless_of_the_source(stereo_wav):
    x = A.decode_mono(stereo_wav)
    assert x.ndim == 1


def test_decode_of_a_missing_file_says_so(tmp_path):
    """Loudly, and naming the file.

    Returning silence instead would be indistinguishable from a quiet passage:
    an empty decode gives duration 0, which sends the renderer to its fallback
    defaults and produces a plausible video of the wrong thing.
    """
    with pytest.raises(A.AudioUnreadable) as e:
        A.decode_mono(tmp_path / "nope.wav")
    assert "nope.wav" in str(e.value)


def test_probe_of_a_missing_file_says_so(tmp_path):
    with pytest.raises(A.AudioUnreadable):
        A.probe_duration(tmp_path / "nope.wav")


# ------------------------------------------------------- signal measurement
# These take arrays, so they need no ffmpeg and no file at all.

def _clicks(bpm: float, seconds: float, sr: int = A.SR) -> np.ndarray:
    """A low-frequency pulse every beat -- what kick detection looks for."""
    x = np.zeros(int(seconds * sr), np.float32)
    period = 60.0 / bpm
    t = np.arange(int(0.04 * sr)) / sr
    click = (np.sin(2 * np.pi * 60 * t) * np.hanning(len(t))).astype(np.float32)
    for k in range(int(seconds / period)):
        i = int(k * period * sr)
        x[i:i + len(click)] += click
    return x


def test_tempo_of_a_120bpm_click_train_measures_120():
    period, bpm = A.estimate_tempo(_clicks(120.0, 16.0))
    assert bpm == pytest.approx(120.0, rel=0.06), f"measured {bpm}"
    assert period == pytest.approx(0.5, rel=0.06)


def test_tempo_of_a_90bpm_click_train_measures_90():
    _period, bpm = A.estimate_tempo(_clicks(90.0, 16.0))
    assert bpm == pytest.approx(90.0, rel=0.08), f"measured {bpm}"


def test_tempo_of_silence_falls_back_rather_than_dividing_by_zero():
    _period, bpm = A.estimate_tempo(np.zeros(A.SR * 4, np.float32))
    assert bpm > 0


def test_tempo_of_a_very_short_clip_falls_back():
    _period, bpm = A.estimate_tempo(np.zeros(64, np.float32))
    assert bpm > 0


def test_a_silent_stretch_is_found_where_it_was_put():
    sr = A.SR
    tone = np.sin(2 * np.pi * 440 * np.arange(2 * sr) / sr).astype(np.float32)
    gap = np.zeros(int(1.5 * sr), np.float32)
    windows = A.find_hold_windows(np.concatenate([tone, gap, tone]))
    assert windows, "a 1.5s silence was not detected at all"
    start, end = windows[0]
    assert start == pytest.approx(2.0, abs=0.3)
    assert end - start == pytest.approx(1.5, abs=0.4)


def test_band_energy_separates_low_from_high():
    sr = A.SR
    t = np.arange(2 * sr) / sr
    low = np.sin(2 * np.pi * 60 * t).astype(np.float32)
    high = np.sin(2 * np.pi * 8000 * t).astype(np.float32)
    assert A._band_rms(low, 20, 150, 50).mean() > A._band_rms(high, 20, 150, 50).mean()
    assert A._band_rms(high, 4000, sr / 2 - 1, 50).mean() > \
           A._band_rms(low, 4000, sr / 2 - 1, 50).mean()


def test_vocal_entry_finds_a_late_start(silence_then_tone):
    """Three seconds of silence, then singing. This is the measurement that
    turns "transcription lost the opening line" into a warning."""
    assert A.vocal_entry(silence_then_tone) == pytest.approx(3.0, abs=0.4)


def test_vocal_entry_of_silence_is_zero(tmp_path, media):
    import subprocess
    p = media / "silent.wav"
    if not p.exists():
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi",
                        "-i", "anullsrc=r=44100:cl=mono:d=2", str(p)], check=True)
    assert A.vocal_entry(p) == 0.0


def test_analysis_of_a_tone_produces_a_complete_record(sine_wav):
    res = A.analyse(sine_wav)
    d = res.to_dict()
    assert d["duration"] == pytest.approx(2.0, rel=0.05)
    assert d["bpm"] > 0
    assert d["beat_period"] > 0, "a zero beat period divides by zero in the field script"


# ------------------------------------------------------------ still measurement

def test_black_reads_as_the_limited_range_floor(half_and_half_png):
    """The whole verify stage subtracts a floor of 16 because ffmpeg reports
    limited-range luma. If that ever stops being true, every brightness
    judgement in the system silently shifts."""
    top = R.region_stats(half_and_half_png, 0, 0, 64, 32)
    assert top["YAVG"] == pytest.approx(16.0, abs=1.5)


def test_white_reads_near_the_limited_range_ceiling(half_and_half_png):
    bottom = R.region_stats(half_and_half_png, 0, 32, 64, 32)
    assert bottom["YAVG"] > 200


def test_a_crop_actually_crops(half_and_half_png):
    whole = R.region_stats(half_and_half_png)
    top = R.region_stats(half_and_half_png, 0, 0, 64, 32)
    bottom = R.region_stats(half_and_half_png, 0, 32, 64, 32)
    assert top["YAVG"] < whole["YAVG"] < bottom["YAVG"]


def test_sample_frames_writes_one_still_per_time(flashes_mp4, tmp_path):
    made = R.sample_frames(flashes_mp4, [1.5, 5.5], tmp_path)
    assert len(made) == 2
    assert all(p.exists() and p.stat().st_size > 0 for p in made)


def test_ffprobe_returns_none_rather_than_raising(tmp_path):
    junk = tmp_path / "not-a-video.mp4"
    junk.write_bytes(b"nonsense")
    assert R._ffprobe(junk) is None


# ------------------------------------------------- does the picture follow the song

def test_the_right_cue_times_score_well(flashes_mp4):
    """The fixture is bright only at 1-2s and 5-6s."""
    out = R.picture_matches_cues(flashes_mp4, [1.0, 5.0], start=0.0)
    assert out["checked"]
    assert out["ratio"] is not None and out["ratio"] > 3, out


def test_the_wrong_cue_times_score_badly(flashes_mp4):
    """This is the failure the check exists for: a render of the wrong part of
    the song, where light and words have nothing to do with each other."""
    out = R.picture_matches_cues(flashes_mp4, [3.0, 8.0], start=0.0)
    assert out["checked"]
    assert out["ratio"] is None or out["ratio"] < 1.5, out


def test_an_all_black_video_is_reported_as_black(black_mp4):
    out = R.picture_matches_cues(black_mp4, [1.0, 3.0], start=0.0)
    assert out["black_fraction"] > 0.9
    assert out["longest_black_seconds"] > 4


def test_with_no_cues_it_still_measures_what_it_can(flashes_mp4):
    """A video type that needs no lyrics still deserves checking. What it
    cannot do without cues is judge whether the picture follows the words, so
    that one number is absent rather than invented."""
    out = R.measure_output(flashes_mp4, [], start=0.0)
    assert out["checked"] is True
    assert "ratio" not in out
    assert "black_fraction" in out and "frame_fill" in out


def test_frame_fill_notices_a_picture_that_draws_short(media, tmp_path):
    """A lost text calibration dropped the row pitch from 53px to 40px, so the
    grid drew short and the bottom third of every frame was empty -- and every
    brightness check still passed, because the part that was drawn was fine."""
    import subprocess
    full = media / "fill_full.mp4"
    short = media / "fill_short.mp4"
    if not full.exists():
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi",
                        "-i", "color=white:size=64x64:rate=10:duration=2",
                        "-pix_fmt", "yuv420p", str(full)], check=True)
    if not short.exists():
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi",
                        "-i", "color=black:size=64x64:rate=10:duration=2",
                        "-vf", "drawbox=0:0:64:20:white:fill",
                        "-pix_fmt", "yuv420p", str(short)], check=True)
    assert R.measure_output(full, [], start=0.0)["frame_fill"] > 0.9
    assert R.measure_output(short, [], start=0.0)["frame_fill"] < 0.5


def test_a_long_render_is_measured_without_buffering_it(black_mp4):
    """Frames are streamed and reduced one at a time. Buffering the decode held
    2.4GB for a four-minute track, so the check meant to make long renders
    trustworthy could not be run on them."""
    import tracemalloc
    tracemalloc.start()
    R.measure_output(black_mp4, [1.0], start=0.0)
    _cur, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    assert peak < 20 * 1024 * 1024, f"peaked at {peak / 1e6:.0f} MB"


def test_longest_run_is_pure_and_correct():
    assert R._longest_run([0, 1, 1, 0, 1, 1, 1, 0]) == 3
    assert R._longest_run([]) == 0
    assert R._longest_run([1, 1]) == 2


# ----------------------------------------------------------------- upload prep

def test_compress_makes_a_small_mono_16k_upload(stereo_wav):
    from lyricfield import transcribe as T
    out = T._compress(stereo_wav)
    info = R._ffprobe(out)
    assert info is not None
    audio = next(s for s in info["streams"] if s.get("codec_type") == "audio")
    assert int(audio.get("channels", 1)) == 1
    assert out.stat().st_size < stereo_wav.stat().st_size


def test_compress_trims_from_the_start(stereo_wav):
    """Seeking is what trims, not a filter: `adelay` with one value moves only
    the first channel, and the downmix then restores the original timing."""
    from lyricfield import transcribe as T
    whole = R._ffprobe(T._compress(stereo_wav, 0.0))
    trimmed = R._ffprobe(T._compress(stereo_wav, 3.0))
    a = float(whole["format"]["duration"])
    b = float(trimmed["format"]["duration"])
    assert a - b == pytest.approx(3.0, abs=0.4)
