"""Every tunable in one place, persisted to TOML.

These values were arrived at by measurement during the TouchDesigner build, not
by taste, and several of them interact in ways that are easy to get wrong:

  * `spark_peak` and `ripple_lift` stack on top of `glow_base` before reaching
    the output. Set naively (0.75 / 0.40) they measured 0.99 at /project1/out --
    indistinguishable from a cued word. Change them together and re-measure.
  * Nothing except a cued word may reach 1.0. `ceil` is the hard cap applied in
    the field script before the glow is composited.
  * `band` rows must fit inside `vrows`. Leaving band < vrows-1 puts dead black
    at the bottom of frame; that bug shipped in three versions.

`validate()` encodes those constraints so the UI can refuse a bad combination
rather than burning a two-minute render to discover it.
"""

from __future__ import annotations

import tomllib
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path


@dataclass
class Grid:
    cols: int = 24
    vrows: int = 24
    band: int = 22
    band_top: int = 1
    font: str = "Courier New"
    font_px: float = 50.0
    width: int = 720
    height: int = 1280


@dataclass
class Look:
    dim_hue: float = 0.58
    dim_sat: float = 0.35
    level_min: float = 0.10
    level_max: float = 0.38
    ceil: float = 0.58          # hard cap for anything not cued
    drift_min: float = 3.0
    drift_max: float = 6.0
    dissolve: float = 2.5
    glow_base: float = 0.62
    glow_lfo: float = 0.08
    glow_low: float = 0.10
    glow_radius: float = 20.0
    glow_lfo_hz: float = 0.06


@dataclass
class Cueing:
    ramp_up: float = 0.12
    hold: float = 0.80
    ramp_dn: float = 0.25
    lead: float = 0.15
    offset: float = 0.0         # global nudge, applied to every cue
    stanza_size: int = 5
    ambient_target: int = 190
    ambient_cycle: float = 6.0
    gap_min: int = 2
    gap_max: int = 4


@dataclass
class Beat:
    ripple_time: float = 0.55
    ripple_sigma: float = 2.2
    ripple_lift: float = 0.14
    spark_time: float = 0.25
    spark_peak: float = 0.52
    spark_frac: float = 0.055
    twinkle_frac_lo: float = 0.04
    twinkle_frac_hi: float = 0.11
    twinkle_decay: float = 0.22
    twinkle_lift: float = 0.20


@dataclass
class Track:
    """Per-song facts. Paths and identity are set when the workspace is created;
    the measured values are filled in by lyricfield.analysis."""
    title: str = ""
    source: str = ""            # the original audio file
    style: str = ""             # slug of the style last applied
    vocals: str = ""
    instrumental: str = ""
    duration: float = 0.0
    kick_in: float = 0.0
    beat_anchor: float = 0.0
    beat_period: float = 0.4615
    high_in: float = 0.0
    hold_windows: list[list[float]] = field(default_factory=list)


@dataclass
class Config:
    grid: Grid = field(default_factory=Grid)
    look: Look = field(default_factory=Look)
    cueing: Cueing = field(default_factory=Cueing)
    beat: Beat = field(default_factory=Beat)
    track: Track = field(default_factory=Track)

    # ---------- io ----------

    @classmethod
    def load(cls, path: str | Path) -> "Config":
        path = Path(path)
        if not path.exists():
            return cls()
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        kw = {}
        for f in fields(cls):
            section = f.default_factory()          # type: ignore[misc]
            for k, v in data.get(f.name, {}).items():
                if hasattr(section, k):
                    setattr(section, k, v)
            kw[f.name] = section
        return cls(**kw)

    def save(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_toml(), encoding="utf-8")

    def to_toml(self) -> str:
        out: list[str] = [
            "# lyricfield configuration.",
            "# Regenerated by the UI; safe to hand-edit. See config.py for the",
            "# constraints between these values.",
            "",
        ]
        for f in fields(self):
            out.append(f"[{f.name}]")
            for k, v in asdict(getattr(self, f.name)).items():
                out.append(f"{k} = {_toml_value(v)}")
            out.append("")
        return "\n".join(out)

    def as_params(self) -> dict:
        """Flat dict injected into TD alongside the field script."""
        p: dict = {}
        for f in fields(self):
            p.update(asdict(getattr(self, f.name)))
        p["hold_windows"] = [tuple(w) for w in self.track.hold_windows]
        return p

    # ---------- constraints ----------

    def validate(self) -> list[str]:
        out: list[str] = []
        g, lk, b, c = self.grid, self.look, self.beat, self.cueing

        if g.band > g.vrows - g.band_top:
            out.append(
                f"band {g.band} + band_top {g.band_top} exceeds vrows {g.vrows}; "
                "rows would fall outside the frame"
            )
        if g.band < g.vrows - g.band_top - 1:
            dead = (g.vrows - g.band_top - g.band) * (g.height / g.vrows)
            out.append(
                f"band {g.band} leaves {dead:.0f}px of dead space at the bottom of "
                f"frame (vrows {g.vrows}) — this shipped as a bug for three versions"
            )
        if lk.level_min >= lk.level_max:
            out.append("level_min must be below level_max")
        if lk.level_max > lk.ceil:
            out.append(f"level_max {lk.level_max} exceeds ceil {lk.ceil}")
        if b.spark_peak > lk.ceil:
            out.append(f"spark_peak {b.spark_peak} exceeds ceil {lk.ceil}")

        # the stacking check that actually caught the 0.99 regression
        stacked = lk.ceil + lk.glow_base * 0.55
        if stacked >= 0.95:
            out.append(
                f"ceil {lk.ceil} plus glow ~{lk.glow_base} will reach ≈{stacked:.2f} at "
                "the output — non-cued cells approach white and stop reading as dim"
            )
        if c.gap_min > c.gap_max:
            out.append("gap_min must not exceed gap_max")
        if c.ambient_target > g.band * g.cols * 0.9:
            out.append(
                f"ambient_target {c.ambient_target} is close to the {g.band * g.cols} "
                "cell capacity; layout will start failing to place lines"
            )
        return out


def _toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    raise TypeError(f"cannot serialise {type(v)}")
