"""The bridge between the repo and the running TouchDesigner project.

Source of truth is the repo. TD holds a thin shell -- a Script TOP, two character
DATs, a cue table DAT, a params DAT, and the render chain -- and everything that
defines behaviour is pushed in from here. Edit `td/field_callbacks.py` in VSCode,
run `push`, see it in TD.

`pull_cues` goes the other way, and exists for recovery: cue tables built by hand
inside a .toe before this package existed can be lifted straight out into a TSV.
"""

from __future__ import annotations

from pathlib import Path

from .config import Config
from .cues import CueTable
from .td_client import TDClient, TDError, TDUnavailable

HERE = Path(__file__).parent

# Operator names inside the TD project. These match the network as it was built
# live, rather than renaming operators TD is actively cooking.
ROOT = "/project1"
SERVER_COMP = "td_mcp_server"
SCRIPT_TOP = f"{ROOT}/v7_script"
CALLBACKS = f"{ROOT}/v7_script_callbacks"
PARAMS_DAT = f"{ROOT}/params"          # created on first push
CUE_DAT = f"{ROOT}/lyrics"
DRUM_DAT = f"{ROOT}/drums"
DIM_DAT = f"{ROOT}/v7_chars_dim"
LIT_DAT = f"{ROOT}/v7_chars_lit"
OUT_TOP = f"{ROOT}/out"

# The two sub-containers a composed render lives in. The module-level paths
# above stay pointed at `/project1` because that is still where a single
# renderer is built and where `render` records from; the pushes below take a
# container so the same code can fill either half.
WORDS_BOX = f"{ROOT}/words"
BEAT_BOX = f"{ROOT}/beat"


def dat(container: str, name: str) -> str:
    """`/project1/beat/params`, from ("/project1/beat", "params")."""
    return f"{container}/{name}"


def _py_repr(v) -> str:
    if isinstance(v, str):
        return repr(v)
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_py_repr(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{_py_repr(k)}: {_py_repr(x)}" for k, x in v.items()) + "}"
    raise TypeError(f"cannot emit {type(v)}")


def params_text(cfg: Config) -> str:
    """The exact text `push_params` writes.

    Separate from the push so a caller can compare what TouchDesigner holds
    against what it should hold. Nothing used to read the params DAT back, so a
    lost write meant every tunable silently fell back to a default.
    """
    p = cfg.as_params()
    body = [
        "# Generated by lyricfield.sync -- do not edit in TouchDesigner.",
        "# Change values in data/config.toml and push again.",
        "",
        "P = {",
    ]
    for k, v in sorted(p.items()):
        body.append(f"    {_py_repr(k)}: {_py_repr(v)},")
    body.append("}")
    return "\n".join(body)


def push_params(client: TDClient, cfg: Config, container: str = ROOT) -> None:
    """Write the config as a Python dict into the params DAT."""
    client.write(dat(container, "params"), params_text(cfg))
    _seed_cue_offset(client, cfg.as_params().get("offset", 0.0))


def _seed_cue_offset(client: TDClient, offset) -> None:
    """Mirror `cueing.offset` onto the Script TOP's custom parameter.

    The field script reads the custom par, because it is the knob you reach for
    while watching playback. Pushing the config has to move it too, or the value
    in the config file is the one thing on screen that is not true.
    """
    try:
        client.call("set", path=SCRIPT_TOP, params={"Cueoffset": float(offset)})
    except TDError:
        pass                        # network built without the par yet


def push_field(client: TDClient, cfg: Config, container: str = ROOT) -> None:
    """Push the active video type's field script into the Script TOP's callbacks DAT.

    Then check it actually runs. Writing the text is not the same as the script
    working, and the difference cost thirty minutes once: a body that raised
    `NameError` on every cook was pushed, reported as success, and the render
    waited out its whole timeout for a file that could never be written.
    """
    src = cfg.video_type.field_source()
    if src is None:
        return                      # a type with no in-TD code is legitimate
    client.write(dat(container, "v7_script_callbacks"), src)
    bad = field_errors(client, container)
    if bad:
        raise TDError(f"the field script does not run:\n{bad}")


def all_field_errors(client: TDClient) -> str:
    """What TouchDesigner says is wrong with ANY of the field scripts.

    A composed render has two, and a layer that raises on every cook is just as
    fatal as a front renderer that does -- the picture stops either way.
    """
    out = []
    for box in field_containers(client):
        bad = field_errors(client, box)
        if bad:
            out.append(f"{box}: {bad}")
    return "\n".join(out)


def field_errors(client: TDClient, container: str = ROOT) -> str:
    """What TouchDesigner says is wrong with the Script TOP, or "".

    Cooks it first, because a script that has not been asked to run yet has no
    errors to report. This is the cheapest possible question -- one round trip,
    no rendering -- and it is the one nothing was asking.
    """
    top = dat(container, "v7_script")
    try:
        client.run(f"def go():\n    o = op({top!r})\n"
                   "    if o is not None:\n        o.cook(force=True)\ngo()")
    except TDError:
        pass
    return client.op_errors(top)


def params_were_read(client: TDClient, container: str = ROOT) -> bool | None:
    """Did the running field script actually parse the params DAT?

    Matching text in the DAT is not the same question, and stopping at it is
    how eleven renderers divided into two camps that could not read each
    other's writing: `sync` writes a Python module, three renderers read it
    through `mod()`, eight parse the text as JSON, and a preview capture wrote
    JSON. Nothing failed. Each script fell back to the defaults compiled into
    it and drew a plausible picture of the wrong look.

    Every field script already records this as `params_missing` in its stats,
    so the answer costs one round trip. Returns None when the script has no
    stats yet -- it has not cooked, which `field_errors` is the check for.
    """
    try:
        out = client.run(
            "def go():\n"
            f"    t = op({container!r} + '/v7_script')\n"
            "    if t is not None:\n"
            "        t.cook(force=True)\n"
            f"    o = op({container!r} + '/v7_script_callbacks')\n"
            "    m = getattr(o, 'module', None) if o is not None else None\n"
            "    st = getattr(m, 'S', {}).get('stats') if m is not None else None\n"
            "    print('' if st is None else int(not st.get('params_missing')))\n"
            "go()").strip()
    except TDError:
        return None
    return bool(int(out)) if out.strip() in ("0", "1") else None


def drums_were_read(client: TDClient, container: str = ROOT) -> dict | None:
    """How many hits of each kind `fx_drive` can actually see.

    The beat-response half of `params_were_read`, and the same class of lie: an
    empty drum table does not fail. `_last` returns -1e9, `_impulse` clamps to
    0.0 on every frame, and the chain renders the word layer untouched while
    reporting success -- so five preset previews came back as five recordings
    of the zoom's idle breathe, all of them passing every check there was.

    `fx_drive` already counts them into its stats, so the answer costs one
    round trip. Returns None when the driver has not cooked and has no stats,
    which `field_errors` is the check for.
    """
    try:
        out = client.run(
            "def go():\n"
            f"    t = op({container!r} + '/fx_drive')\n"
            "    if t is not None:\n"
            "        t.cook(force=True)\n"
            f"    o = op({container!r} + '/fx_drive_callbacks')\n"
            "    m = getattr(o, 'module', None) if o is not None else None\n"
            "    st = getattr(m, 'S', {}).get('stats') if m is not None else None\n"
            "    print('' if st is None else repr(st.get('drums') or {}))\n"
            "go()").strip()
    except TDError:
        return None
    if not out:
        return None
    try:
        got = eval(out)
    except Exception:
        return None
    return got if isinstance(got, dict) else None


def push_cues(client: TDClient, table: CueTable, container: str = ROOT) -> None:
    client.write(dat(container, "lyrics"), table.to_dat_text())


def push_drums(client: TDClient, table, container: str = ROOT) -> None:
    """Write the detected drum hits into the network.

    The field scripts look these up by time instead of evaluating the analysis
    CHOP, so the beat response is the same in a preview as in a render and does
    not depend on how fast TouchDesigner happens to be cooking.
    """
    client.write(dat(container, "drums"), table.to_dat_text())


def pull_drums(client: TDClient, dat: str = DRUM_DAT):
    from .drums import DrumTable
    return DrumTable.from_dat_text(client.dat_text(dat))


def pull_cues(client: TDClient, dat: str = CUE_DAT) -> CueTable:
    """Recover a cue table that only exists inside a .toe.

    Uses `dat_text`, not `read` -- the read tool formats for display and prefixes
    each line with its number, which silently shifts every column when parsed.
    """
    return CueTable.from_dat_text(client.dat_text(dat))


# Where a field script can live. A composed render has one per half; a project
# built before compositing has one at the root. Asking TouchDesigner which of
# them exist is cheaper than threading the config through `render`, and it is
# right for both shapes.
FIELD_BOXES = (WORDS_BOX, BEAT_BOX, ROOT)


def field_containers(client: TDClient) -> list[str]:
    """The containers that actually hold a Script TOP, nearest half first."""
    want = list(FIELD_BOXES)
    try:
        out = client.run(
            "def go():\n"
            f"    boxes = {want!r}\n"
            "    print([b for b in boxes if op(b + '/v7_script') is not None])\n"
            "go()")
    except TDError:
        return [ROOT]
    try:
        found = [b for b in eval(out.strip()) if isinstance(b, str)]
    except Exception:
        found = []
    return found or [ROOT]


def reset_field_state(client: TDClient) -> None:
    """Clear every field script's cached layout so the next cook rebuilds.

    Every one, because a composed render has two and clearing only the root's
    would leave the layer drawing from a stale grid.
    """
    for box in field_containers(client):
        client.run(
            "def main():\n"
            f"    d = op({dat(box, 'v7_script_callbacks')!r})\n"
            "    if d is None:\n"
            "        return 'no callbacks DAT'\n"
            # `d.module` compiles the DAT, so it raises on one that is empty or
            # half-written -- which is exactly the state a container is in when
            # a run died before pushing its field script. This runs BEFORE the
            # push that would fix that, so it must not depend on it: a wrecked
            # container has no cached state to clear anyway.
            "    try:\n"
            "        m = d.module\n"
            "    except Exception as e:\n"
            "        return 'no module yet (%s)' % type(e).__name__\n"
            "    if hasattr(m, 'S'):\n"
            "        m.S.clear()\n"
            "    return 'cleared'\n"
            "print(main())"
        )


def reset_drive_state(client: TDClient, container: str = ROOT) -> None:
    """`reset_field_state`'s other half, for the beat chain.

    `fx_drive` reads the drum table once and keeps it -- `if 'drums' not in S`
    -- and clears `S` only when the params text changes length. So a table
    pushed after the driver has cooked is never seen: it caches the empty one
    that `compose.network` created and drives nothing, for the life of the
    project. `reset_field_state` walks `v7_script_callbacks` and has never
    touched this DAT, and in `push_composed` the ordering makes it right only
    by accident -- the callbacks are rewritten after the drums, which reloads
    the module and wipes `S` on the way past.
    """
    client.run(
        "def main():\n"
        f"    d = op({dat(container, 'fx_drive_callbacks')!r})\n"
        "    if d is None:\n"
        "        return 'no driver here'\n"
        # Same guard as `reset_field_state`: `.module` compiles, so it raises
        # rather than returning None on a DAT that has not been written yet.
        "    try:\n"
        "        m = d.module\n"
        "    except Exception as e:\n"
        "        return 'no module yet (%s)' % type(e).__name__\n"
        "    if m is not None and hasattr(m, 'S'):\n"
        "        m.S.clear()\n"
        "    return 'cleared'\n"
        "print(main())"
    )


def quiesce(client: TDClient) -> None:
    """Stop playback and bypass the heavy Script TOP.

    TD blocks its web server thread while the Script TOP cooks, and the script
    runs CookLevel.ALWAYS -- so it keeps working even with the timeline stopped.
    Saving without doing this reliably stalls TD for one to three minutes.
    """
    client.run(
        "def main():\n"
        "    me.time.play = 0\n"
        f"    sc = op({SCRIPT_TOP!r})\n"
        "    if sc is not None:\n"
        "        sc.bypass = True\n"
        "    return 'quiesced'\n"
        "print(main())"
    )


def resume(client: TDClient) -> None:
    """Undo `quiesce`: un-bypass the Script TOP *and* restart playback.

    Leaving playback stopped is not harmless. A render finalizes on a
    `delayFrames` timer, which only advances while the timeline runs, so a
    quiesce that is never resumed strands the next render and leaves
    `_mcp_movieout` in the network with its frames on disk.
    """
    client.run(
        "def main():\n"
        f"    sc = op({SCRIPT_TOP!r})\n"
        "    if sc is not None:\n"
        "        sc.bypass = False\n"
        "    me.time.play = 1\n"
        "    return 'resumed'\n"
        "print(main())"
    )


def save_project(client: TDClient, timeout: float = 420.0) -> str:
    """Save, tolerating the stall. TD often stops answering mid-save for minutes
    and then completes normally, so a timeout here is not a failure."""
    quiesce(client)
    try:
        client.run(
            "import os\n"
            "project.save(os.path.join(project.folder, project.name))\n"
            "print(project.name)",
            timeout=timeout,
        )
        return "saved"
    except Exception:
        if client.wait_until_ready(seconds=timeout):
            return "saved (TD stalled during write, then recovered)"
        raise
    finally:
        # quiesce() stopped playback and bypassed the field; without this the
        # project is left visually dead until something else happens to park it.
        try:
            resume(client)
        except Exception:
            pass


def project_path(client: TDClient) -> str:
    """The .toe TouchDesigner currently has open."""
    return client.run(
        "def main():\n"
        "    import os\n"
        "    return os.path.join(project.folder, project.name)\n"
        "print(main())"
    ).strip()


TOE_TOOLS = Path("/Applications/TouchDesigner.app/Contents/MacOS")


def _toeexpand() -> Path | None:
    """TouchDesigner's .toe/.tox expander, if this install has it."""
    for cand in (TOE_TOOLS / "toeexpand",
                 Path("/opt/TouchDesigner/bin/toeexpand"),
                 Path("C:/Program Files/Derivative/TouchDesigner/bin/toeexpand.exe")):
        if cand.exists():
            return cand
    return None


def has_server(path: str | Path) -> bool:
    """Does this .toe contain an MCP server component?

    Checked before every load, because loading a project without one takes the
    server down with the old project and never brings it back -- there is then
    no way to drive TouchDesigner at all, by any means.

    A .toe is compressed, so the operator name is not findable in the raw bytes.
    TouchDesigner ships `toeexpand`, which unpacks a project into a directory and
    writes a table of contents listing every operator; reading that answers the
    question in about a fifth of a second without opening the file in TD.
    """
    import subprocess
    import tempfile

    path = Path(path)
    if not path.exists():
        return False
    exe = _toeexpand()
    if exe is None:
        return False            # cannot prove it is safe, so do not claim it is
    with tempfile.TemporaryDirectory() as tmp:
        local = Path(tmp) / path.name
        try:
            local.write_bytes(path.read_bytes())
            subprocess.run([str(exe), local.name], cwd=tmp,
                           capture_output=True, timeout=120)
            toc = local.with_suffix(".toe.toc")
            if not toc.exists():
                return False
            return SERVER_COMP in toc.read_text(errors="replace")
        except (OSError, subprocess.SubprocessError):
            return False


def save_project_as(client: TDClient, path: str | Path,
                    timeout: float = 420.0) -> str:
    """Save the open project to a new path; TouchDesigner continues in the new file.

    Tolerates the stall: TD routinely stops answering mid-save for minutes and
    then completes normally, so a timeout here is a wait, not a failure.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    quiesce(client)
    try:
        client.run(f"project.save({str(path)!r})\nprint(project.name)",
                   timeout=timeout)
    except Exception:
        if not client.wait_until_ready(seconds=timeout):
            raise
    finally:
        try:
            resume(client)
        except Exception:
            pass
    if not path.exists():
        raise TDError(f"TouchDesigner reported saving but {path} does not exist")
    return project_path(client)


def load_project(client: TDClient, path: str | Path, timeout: float = 420.0) -> str:
    """Open a project and wait for the MCP server to come back with it.

    Refuses to load a file that has no server rather than losing control of
    TouchDesigner; that failure is unrecoverable without a human.
    """
    path = Path(path)
    if not path.exists():
        raise TDError(f"no such project: {path}")
    if not has_server(path):
        raise TDError(
            f"{path} has no {SERVER_COMP} component. Loading it would take the "
            "MCP server down with no way to bring it back."
        )
    try:
        client.run(f"project.load({str(path)!r})\nprint('loading')", timeout=30.0)
    except Exception:
        pass                    # the server goes down mid-call; that is expected
    if not client.wait_until_ready(seconds=timeout):
        raise TDUnavailable(f"TouchDesigner did not come back after loading {path}")
    return project_path(client)


def set_timeline_length(client: TDClient, seconds: float,
                        exact: bool = False) -> dict:
    """Make the timeline at least `seconds` long, or exactly that long.

    Growing is the safe default: shrinking would cut a longer song that is
    already loaded. TouchDesigner loops silently at the end of the timeline, so
    a project shorter than its track renders the wrong thing with no error.

    `exact=True` is for the one caller that knows the authoritative length --
    provisioning, which has the song's measured duration in hand. Without it a
    timeline can only ever ratchet upwards: a project that inherited a wrong
    length, or one left stretched by an earlier song, stays that way forever.

    **`end` is not enough.** The timeline also has a play range -- `rangestart`
    to `rangeend` -- and with `rangelimit` at "loop" the playhead simply cannot
    leave it. Inherited from the 90s benchmark song, `rangeend` sat at frame
    5433 while `end` was 16074, so on a 264s track:

      * setting the frame past 5433 silently snapped back (`+= 100` moved,
        `= 10332` did not, which is what made this visible at all);
      * the preview seek to 2:45 wrapped round to about 1:20 and rendered a
        part of the song nobody asked for, with words that did not match the
        moment -- reported, reasonably, as "the lyrics are not glowing".

    Nothing errors in either case. Both have to be set.
    """
    out = client.run(
        "def main():\n"
        f"    want = int({float(seconds)!r} * me.time.rate) + 1\n"
        "    t = op('/local/time') or me.time\n"
        "    before = (t.end, t.par.rangeend.eval())\n"
        f"    exact = {bool(exact)!r}\n"
        "    if exact or t.end < want:\n"
        "        t.end = want\n"
        "    if t.par.rangestart.eval() > 1:\n"
        "        t.par.rangestart = 1\n"
        "    if exact or t.par.rangeend.eval() < t.end:\n"
        "        t.par.rangeend = t.end\n"
        "    return repr({'rate': t.rate, 'was_end': before[0],\n"
        "                 'was_range_end': before[1], 'now': t.end,\n"
        "                 'range_end': t.par.rangeend.eval(),\n"
        "                 'seconds': round(t.end / t.rate, 1)})\n"
        "print(main())"
    ).strip()
    try:
        return eval(out)
    except Exception:
        return {"raw": out}


def timeline_state(client: TDClient) -> dict:
    """What the timeline is, as opposed to what it was told to be.

    `end` is the length and `rangestart`..`rangeend` is where the playhead may
    go. They are set separately and only the first was ever set, so a project
    could be long enough and still refuse to play past 90 seconds.
    """
    out = client.run(
        "def main():\n"
        "    t = op('/local/time') or me.time\n"
        "    return repr({'rate': float(t.rate), 'end': int(t.end),\n"
        "                 'range_start': int(t.par.rangestart.eval()),\n"
        "                 'range_end': int(t.par.rangeend.eval()),\n"
        "                 'limit': str(t.par.rangelimit.eval())})\n"
        "print(main())"
    ).strip()
    try:
        d = eval(out)
    except Exception:
        return {"raw": out}
    rate = d.get("rate") or 60.0
    d["range_ok"] = d["range_start"] <= 1 and d["range_end"] >= d["end"]
    # What the playhead can actually reach, which is the range, not the length.
    d["covers_seconds"] = round(min(d["end"], d["range_end"]) / rate, 2)
    return d


def push_composed(client: TDClient, cfg: Config, table: CueTable | None = None,
                  drums=None) -> list[str]:
    """Fill the word container and the beat response chain.

    The renderer's own params and field script go into `/project1/words`; the
    response's go beside the chain at the root, because the chain is not part of
    any renderer -- that is what lets one preset work with all eight.
    """
    from . import compose

    box = compose.container_for(cfg)
    done: list[str] = []
    push_params(client, cfg, box)
    push_field(client, cfg, box)
    done.append(f"{cfg.type} into words")

    if table is not None and cfg.video_type.needs_lyrics:
        push_cues(client, table, box)
        done.append(f"{len(table.cues)} cues")
    if drums is not None:
        # Both halves: the renderer answers the drums inside its picture, and
        # the chain answers them outside it.
        push_drums(client, drums, box)
        push_drums(client, drums, ROOT)
        done.append(f"{len(drums)} drum hits")

    client.write(dat(ROOT, "fx_drive_callbacks"), compose.drive_source())
    client.write(dat(ROOT, "fx_params"), params_module(compose.drive_params(cfg)))
    done.append(f"beat: {cfg.beat_preset}")

    reset_field_state(client)
    done.append("state reset")
    return done


def params_module(p: dict) -> str:
    """The same module form `params_text` writes, for a plain dict.

    Every field script reads its DAT through the prelude's `_read_params`,
    which accepts this form and JSON; one writer keeps them from drifting."""
    body = ["# Generated by lyricfield.sync -- do not edit in TouchDesigner.",
            "", "P = {"]
    for k, v in sorted(p.items()):
        body.append(f"    {_py_repr(k)}: {_py_repr(v)},")
    body.append("}")
    return "\n".join(body)


def push_all(client: TDClient, cfg: Config, table: CueTable | None = None,
             drums=None) -> list[str]:
    done: list[str] = []
    push_params(client, cfg); done.append(f"params ({cfg.type})")
    push_field(client, cfg); done.append("field script")
    if table is not None:
        push_cues(client, table); done.append(f"{len(table.cues)} cues")
    if drums is not None:
        push_drums(client, drums); done.append(f"{len(drums)} drum hits")
    reset_field_state(client); done.append("state reset")
    return done
