"""The bridge between the repo and the running TouchDesigner project.

Source of truth is the repo. TD holds a thin shell -- a Script TOP, two character
DATs, a cue table DAT, a params DAT, and the render chain -- and everything that
defines behaviour is pushed in from here. Edit `td/field_callbacks.py` in VSCode,
run `push`, see it in TD.

`pull_cues` goes the other way, and exists for recovery: cue tables built by hand
inside a .toe before this package existed can be lifted straight out into a TSV.
"""

from __future__ import annotations

from pathlib import Path

from .config import Config
from .cues import CueTable
from .td_client import TDClient, TDError, TDUnavailable

HERE = Path(__file__).parent

# Operator names inside the TD project. These match the network as it was built
# live, rather than renaming operators TD is actively cooking.
ROOT = "/project1"
SERVER_COMP = "td_mcp_server"
SCRIPT_TOP = f"{ROOT}/v7_script"
CALLBACKS = f"{ROOT}/v7_script_callbacks"
PARAMS_DAT = f"{ROOT}/params"          # created on first push
CUE_DAT = f"{ROOT}/lyrics"
DRUM_DAT = f"{ROOT}/drums"
BAND_DAT = f"{ROOT}/bands"
DIM_DAT = f"{ROOT}/v7_chars_dim"
LIT_DAT = f"{ROOT}/v7_chars_lit"
OUT_TOP = f"{ROOT}/out"


def _py_repr(v) -> str:
    if isinstance(v, str):
        return repr(v)
    if isinstance(v, bool):
        return "True" if v else "False"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_py_repr(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{_py_repr(k)}: {_py_repr(x)}" for k, x in v.items()) + "}"
    raise TypeError(f"cannot emit {type(v)}")


def params_text(cfg: Config) -> str:
    """The exact text `push_params` writes.

    Separate from the push so a caller can compare what TouchDesigner holds
    against what it should hold. Nothing used to read the params DAT back, so a
    lost write meant every tunable silently fell back to a default.
    """
    p = cfg.as_params()
    body = [
        "# Generated by lyricfield.sync -- do not edit in TouchDesigner.",
        "# Change values in data/config.toml and push again.",
        "",
        "P = {",
    ]
    for k, v in sorted(p.items()):
        body.append(f"    {_py_repr(k)}: {_py_repr(v)},")
    body.append("}")
    return "\n".join(body)


def push_params(client: TDClient, cfg: Config) -> None:
    """Write the config as a Python dict into the params DAT."""
    client.write(PARAMS_DAT, params_text(cfg))
    _seed_cue_offset(client, cfg.as_params().get("offset", 0.0))


def _seed_cue_offset(client: TDClient, offset) -> None:
    """Mirror `cueing.offset` onto the Script TOP's custom parameter.

    The field script reads the custom par, because it is the knob you reach for
    while watching playback. Pushing the config has to move it too, or the value
    in the config file is the one thing on screen that is not true.
    """
    try:
        client.call("set", path=SCRIPT_TOP, params={"Cueoffset": float(offset)})
    except TDError:
        pass                        # network built without the par yet


def push_field(client: TDClient, cfg: Config) -> None:
    """Push the active video type's field script into the Script TOP's callbacks DAT.

    Then check it actually runs. Writing the text is not the same as the script
    working, and the difference cost thirty minutes once: a body that raised
    `NameError` on every cook was pushed, reported as success, and the render
    waited out its whole timeout for a file that could never be written.
    """
    src = cfg.video_type.field_source()
    if src is None:
        return                      # a type with no in-TD code is legitimate
    client.write(CALLBACKS, src)
    bad = field_errors(client)
    if bad:
        raise TDError(f"the field script does not run:\n{bad}")


def field_errors(client: TDClient) -> str:
    """What TouchDesigner says is wrong with the Script TOP, or "".

    Cooks it first, because a script that has not been asked to run yet has no
    errors to report. This is the cheapest possible question -- one round trip,
    no rendering -- and it is the one nothing was asking.
    """
    try:
        client.run(f"def go():\n    o = op({SCRIPT_TOP!r})\n"
                   "    if o is not None:\n        o.cook(force=True)\ngo()")
    except TDError:
        pass
    return client.op_errors(SCRIPT_TOP)


def params_were_read(client: TDClient, container: str = ROOT) -> bool | None:
    """Did the running field script actually parse the params DAT?

    Matching text in the DAT is not the same question, and stopping at it is
    how eleven renderers divided into two camps that could not read each
    other's writing: `sync` writes a Python module, three renderers read it
    through `mod()`, eight parse the text as JSON, and a preview capture wrote
    JSON. Nothing failed. Each script fell back to the defaults compiled into
    it and drew a plausible picture of the wrong look.

    Every field script already records this as `params_missing` in its stats,
    so the answer costs one round trip. Returns None when the script has no
    stats yet -- it has not cooked, which `field_errors` is the check for.
    """
    try:
        out = client.run(
            "def go():\n"
            f"    t = op({container!r} + '/v7_script')\n"
            "    if t is not None:\n"
            "        t.cook(force=True)\n"
            f"    o = op({container!r} + '/v7_script_callbacks')\n"
            "    m = getattr(o, 'module', None) if o is not None else None\n"
            "    st = getattr(m, 'S', {}).get('stats') if m is not None else None\n"
            "    print('' if st is None else int(not st.get('params_missing')))\n"
            "go()").strip()
    except TDError:
        return None
    return bool(int(out)) if out.strip() in ("0", "1") else None


def push_cues(client: TDClient, table: CueTable) -> None:
    client.write(CUE_DAT, table.to_dat_text())


def push_drums(client: TDClient, table) -> None:
    """Write the detected drum hits into the network.

    The field scripts look these up by time instead of evaluating the analysis
    CHOP, so the beat response is the same in a preview as in a render and does
    not depend on how fast TouchDesigner happens to be cooking.
    """
    client.write(DRUM_DAT, table.to_dat_text())


def push_bands(client: TDClient, table) -> None:
    """Write the measured spectrum into the network.

    Measured offline for the same reason the drums are: a spectrum taken live
    inside TouchDesigner depends on how fast it happens to be cooking, so a
    preview and a render of the same second would not agree.
    """
    client.write(BAND_DAT, table.to_dat_text())


def pull_bands(client: TDClient, dat: str = BAND_DAT):
    from .bands import BandTable
    return BandTable.from_dat_text(client.dat_text(dat))


def pull_drums(client: TDClient, dat: str = DRUM_DAT):
    from .drums import DrumTable
    return DrumTable.from_dat_text(client.dat_text(dat))


def pull_cues(client: TDClient, dat: str = CUE_DAT) -> CueTable:
    """Recover a cue table that only exists inside a .toe.

    Uses `dat_text`, not `read` -- the read tool formats for display and prefixes
    each line with its number, which silently shifts every column when parsed.
    """
    return CueTable.from_dat_text(client.dat_text(dat))


def reset_field_state(client: TDClient) -> None:
    """Clear the field script's cached layout so the next cook rebuilds."""
    client.run(
        "def main():\n"
        f"    d = op({CALLBACKS!r})\n"
        "    if d is None:\n"
        "        return 'no callbacks DAT'\n"
        "    m = d.module\n"
        "    if hasattr(m, 'S'):\n"
        "        m.S.clear()\n"
        "    return 'cleared'\n"
        "print(main())"
    )


def quiesce(client: TDClient) -> None:
    """Stop playback and bypass the heavy Script TOP.

    TD blocks its web server thread while the Script TOP cooks, and the script
    runs CookLevel.ALWAYS -- so it keeps working even with the timeline stopped.
    Saving without doing this reliably stalls TD for one to three minutes.
    """
    client.run(
        "def main():\n"
        "    me.time.play = 0\n"
        f"    sc = op({SCRIPT_TOP!r})\n"
        "    if sc is not None:\n"
        "        sc.bypass = True\n"
        "    return 'quiesced'\n"
        "print(main())"
    )


def resume(client: TDClient) -> None:
    """Undo `quiesce`: un-bypass the Script TOP *and* restart playback.

    Leaving playback stopped is not harmless. A render finalizes on a
    `delayFrames` timer, which only advances while the timeline runs, so a
    quiesce that is never resumed strands the next render and leaves
    `_mcp_movieout` in the network with its frames on disk.
    """
    client.run(
        "def main():\n"
        f"    sc = op({SCRIPT_TOP!r})\n"
        "    if sc is not None:\n"
        "        sc.bypass = False\n"
        "    me.time.play = 1\n"
        "    return 'resumed'\n"
        "print(main())"
    )


def save_project(client: TDClient, timeout: float = 420.0) -> str:
    """Save, tolerating the stall. TD often stops answering mid-save for minutes
    and then completes normally, so a timeout here is not a failure."""
    quiesce(client)
    try:
        client.run(
            "import os\n"
            "project.save(os.path.join(project.folder, project.name))\n"
            "print(project.name)",
            timeout=timeout,
        )
        return "saved"
    except Exception:
        if client.wait_until_ready(seconds=timeout):
            return "saved (TD stalled during write, then recovered)"
        raise
    finally:
        # quiesce() stopped playback and bypassed the field; without this the
        # project is left visually dead until something else happens to park it.
        try:
            resume(client)
        except Exception:
            pass


def project_path(client: TDClient) -> str:
    """The .toe TouchDesigner currently has open."""
    return client.run(
        "def main():\n"
        "    import os\n"
        "    return os.path.join(project.folder, project.name)\n"
        "print(main())"
    ).strip()


TOE_TOOLS = Path("/Applications/TouchDesigner.app/Contents/MacOS")


def _toeexpand() -> Path | None:
    """TouchDesigner's .toe/.tox expander, if this install has it."""
    for cand in (TOE_TOOLS / "toeexpand",
                 Path("/opt/TouchDesigner/bin/toeexpand"),
                 Path("C:/Program Files/Derivative/TouchDesigner/bin/toeexpand.exe")):
        if cand.exists():
            return cand
    return None


def has_server(path: str | Path) -> bool:
    """Does this .toe contain an MCP server component?

    Checked before every load, because loading a project without one takes the
    server down with the old project and never brings it back -- there is then
    no way to drive TouchDesigner at all, by any means.

    A .toe is compressed, so the operator name is not findable in the raw bytes.
    TouchDesigner ships `toeexpand`, which unpacks a project into a directory and
    writes a table of contents listing every operator; reading that answers the
    question in about a fifth of a second without opening the file in TD.
    """
    import subprocess
    import tempfile

    path = Path(path)
    if not path.exists():
        return False
    exe = _toeexpand()
    if exe is None:
        return False            # cannot prove it is safe, so do not claim it is
    with tempfile.TemporaryDirectory() as tmp:
        local = Path(tmp) / path.name
        try:
            local.write_bytes(path.read_bytes())
            subprocess.run([str(exe), local.name], cwd=tmp,
                           capture_output=True, timeout=120)
            toc = local.with_suffix(".toe.toc")
            if not toc.exists():
                return False
            return SERVER_COMP in toc.read_text(errors="replace")
        except (OSError, subprocess.SubprocessError):
            return False


def save_project_as(client: TDClient, path: str | Path,
                    timeout: float = 420.0) -> str:
    """Save the open project to a new path; TouchDesigner continues in the new file.

    Tolerates the stall: TD routinely stops answering mid-save for minutes and
    then completes normally, so a timeout here is a wait, not a failure.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    quiesce(client)
    try:
        client.run(f"project.save({str(path)!r})\nprint(project.name)",
                   timeout=timeout)
    except Exception:
        if not client.wait_until_ready(seconds=timeout):
            raise
    finally:
        try:
            resume(client)
        except Exception:
            pass
    if not path.exists():
        raise TDError(f"TouchDesigner reported saving but {path} does not exist")
    return project_path(client)


def load_project(client: TDClient, path: str | Path, timeout: float = 420.0) -> str:
    """Open a project and wait for the MCP server to come back with it.

    Refuses to load a file that has no server rather than losing control of
    TouchDesigner; that failure is unrecoverable without a human.
    """
    path = Path(path)
    if not path.exists():
        raise TDError(f"no such project: {path}")
    if not has_server(path):
        raise TDError(
            f"{path} has no {SERVER_COMP} component. Loading it would take the "
            "MCP server down with no way to bring it back."
        )
    try:
        client.run(f"project.load({str(path)!r})\nprint('loading')", timeout=30.0)
    except Exception:
        pass                    # the server goes down mid-call; that is expected
    if not client.wait_until_ready(seconds=timeout):
        raise TDUnavailable(f"TouchDesigner did not come back after loading {path}")
    return project_path(client)


def set_timeline_length(client: TDClient, seconds: float,
                        exact: bool = False) -> dict:
    """Make the timeline at least `seconds` long, or exactly that long.

    Growing is the safe default: shrinking would cut a longer song that is
    already loaded. TouchDesigner loops silently at the end of the timeline, so
    a project shorter than its track renders the wrong thing with no error.

    `exact=True` is for the one caller that knows the authoritative length --
    provisioning, which has the song's measured duration in hand. Without it a
    timeline can only ever ratchet upwards: a project that inherited a wrong
    length, or one left stretched by an earlier song, stays that way forever.

    **`end` is not enough.** The timeline also has a play range -- `rangestart`
    to `rangeend` -- and with `rangelimit` at "loop" the playhead simply cannot
    leave it. Inherited from the 90s benchmark song, `rangeend` sat at frame
    5433 while `end` was 16074, so on a 264s track:

      * setting the frame past 5433 silently snapped back (`+= 100` moved,
        `= 10332` did not, which is what made this visible at all);
      * the preview seek to 2:45 wrapped round to about 1:20 and rendered a
        part of the song nobody asked for, with words that did not match the
        moment -- reported, reasonably, as "the lyrics are not glowing".

    Nothing errors in either case. Both have to be set.
    """
    out = client.run(
        "def main():\n"
        f"    want = int({float(seconds)!r} * me.time.rate) + 1\n"
        "    t = op('/local/time') or me.time\n"
        "    before = (t.end, t.par.rangeend.eval())\n"
        f"    exact = {bool(exact)!r}\n"
        "    if exact or t.end < want:\n"
        "        t.end = want\n"
        "    if t.par.rangestart.eval() > 1:\n"
        "        t.par.rangestart = 1\n"
        "    if exact or t.par.rangeend.eval() < t.end:\n"
        "        t.par.rangeend = t.end\n"
        "    return repr({'rate': t.rate, 'was_end': before[0],\n"
        "                 'was_range_end': before[1], 'now': t.end,\n"
        "                 'range_end': t.par.rangeend.eval(),\n"
        "                 'seconds': round(t.end / t.rate, 1)})\n"
        "print(main())"
    ).strip()
    try:
        return eval(out)
    except Exception:
        return {"raw": out}


def timeline_state(client: TDClient) -> dict:
    """What the timeline is, as opposed to what it was told to be.

    `end` is the length and `rangestart`..`rangeend` is where the playhead may
    go. They are set separately and only the first was ever set, so a project
    could be long enough and still refuse to play past 90 seconds.
    """
    out = client.run(
        "def main():\n"
        "    t = op('/local/time') or me.time\n"
        "    return repr({'rate': float(t.rate), 'end': int(t.end),\n"
        "                 'range_start': int(t.par.rangestart.eval()),\n"
        "                 'range_end': int(t.par.rangeend.eval()),\n"
        "                 'limit': str(t.par.rangelimit.eval())})\n"
        "print(main())"
    ).strip()
    try:
        d = eval(out)
    except Exception:
        return {"raw": out}
    rate = d.get("rate") or 60.0
    d["range_ok"] = d["range_start"] <= 1 and d["range_end"] >= d["end"]
    # What the playhead can actually reach, which is the range, not the length.
    d["covers_seconds"] = round(min(d["end"], d["range_end"]) / rate, 2)
    return d


def push_all(client: TDClient, cfg: Config, table: CueTable | None = None,
             drums=None, bands=None) -> list[str]:
    done: list[str] = []
    push_params(client, cfg); done.append(f"params ({cfg.type})")
    push_field(client, cfg); done.append("field script")
    if table is not None:
        push_cues(client, table); done.append(f"{len(table.cues)} cues")
    if drums is not None:
        push_drums(client, drums); done.append(f"{len(drums)} drum hits")
    if bands is not None:
        push_bands(client, bands); done.append(f"{len(bands)} band slices")
    reset_field_state(client); done.append("state reset")
    return done
